### ISSUE TITLE
Yoigoshi-hen #6 Chapter missing choice

### ISSUE THREAD

**Issue by sushyoshi** [masagrator/HigurashiENX#4]
I have been playing through Yoigochi-hen chapter and cannot make the option appear for che true ending. Is there a bug with the translation that is interfering with the appearance of this choice?

**Comment by masagrator** [comment]
You sure about that you are talking about #6, not #6B? 

Chapter 4 has two choices - first one leads to true end and BAD END 1, second choice leads you to BAD END 2 & BAD END 3.
First choice leads you to chapters 5, 6, 7, etc.
Second choice to 5B, 6B, 7B.

**Comment by sushyoshi** [comment]
I am sure it's #6.
At chapter 4 when choosing first choice it only leads me to BAD END 1. I know there is supposed to be a choice to "WAIT" or "FOLLOW" but these options are never triggered and I automatically go into the BAD END 1 route. 
 I was wondering if it's a bug or is there some very specific requirement to unlock the trigger of that choice. So far I have completed all previous chapters, except the one not translated, which I could bypass.
 Sorry if this is not the right place to ask this but I really cannot find any walkthrough or guide in English for the switch version of the game so I was hoping people that are using the Switch version along with your translation mod would be able to help out.

**Comment by masagrator** [comment]
It's possible that something was not triggered in one of previous stories and that's why you are getting automatically jumped to bad end.
I will try to check assembly if I can find any instruction related to jump.

**Comment by masagrator** [comment]
Yup, there is some check for flag:
```asm
LAB_95b134:
        SGET @0x0002, 32n
        jeq @0x0002, 0n, LAB_96caca
LAB_95b140:
        SELECT 102s, 50s, @0x0000, 4095n, S"園崎さんに声をかけた", S["俺も、一緒に行きます。","俺は、ここで待っています。"]
        jeq @0x0000, 0n, LAB_96caca
        j LAB_9752ec
```
I will try to find which one is using it

**Comment by masagrator** [comment]
OK, found it.
```asm
        SSET 32n, 1n
```
It's in Common Route -> Mion Route 4 `#2`
If you will get this line at the end of chapter
https://github.com/masagrator/HigurashiENX-texts/blob/099628568f1632903a6822e0b7f637d1b2ac3c81/common_mion4_2.json#L5754
Then it will be triggered. Dunno which choices lead to this line exactly, but now you have a point what you need to accomplish.

**Comment by masagrator** [comment]
Remember to save game manually after triggering this flag, otherwise it won't be saved.

**Comment by sushyoshi** [comment]
Thanks for taking the time and effort help on this, even though it's not related to your mod. 
Even though I completed Mion Route 4 #2 , and going to the end of the route and also manually saving did not help.
 However, when I restarted the Common Route, instead of going through the Scenario, I played it all from the beginning, I was able to access dialog not yet read. Then I completed the route as you suggested until the end. I noticed that, after the credits rolled, the main screen music has changed, and that was the first sign that something as in fact changed from before. 
In the end now I am able to access the required choices that I was missing before.
 From what I concluded, it seems using the Scenario chart to jump through routes for different choices is not the best approach since there will be some missing dialog and I therefore unlock triggers missing this way. So my best bet is to start each chapter again and fast forward until new dialog/choices appear 

Thanks again for all the help.

**Comment by gut5** [comment]
@sushyoshi this was a few years ago now, can you remember the steps you took to get through Yoigoshi? I am having the exact same issue as you except when I got the dialogue for Mion "After that, Mion's grumblings were unrelenting..." I still can't get the true ending for Yoigoshi. 
I have tried the other things you suggested like starting from Common Route and then seeing if I can unlock new dialogue but there's nothing left to unlock.

@masagrator are you definitely sure that the Mion "grumbling" dialogue would unlock the Yoigoshi ending?
