### ISSUE TITLE
Update 2.0.0 released

### ISSUE THREAD

**Issue by SphericalSector** [masagrator/HigurashiENX#9]
I received update 2.0.0 of the game on my Switch earlier, any plans to support the new update or the new dlc mode? Thanks a lot.

**Comment by masagrator** [comment]
I will go with path of lowest resistance. I won't add translation for new scenario, I will update mod to support newest version.

**Comment by SphericalSector** [comment]
Sounds great, thanks! Do you have any idea yet if the translation will work for the new origin mode (not new scenario)?

**Comment by masagrator** [comment]
No idea. I won't find out for next 7 days anyway.

I am waiting for info from other person about technical changes in files. The worst case is if they made separate scenario file for NVL mode and if they changed opcodes.

**Comment by UR2L8** [comment]
> I will go with path of lowest resistance. I won't add translation for new scenario, I will update mod to support newest version.

Thank you for your quick response to this.
I literally JUST imported a hard copy, so I'm more than eager to get started.

**Comment by UR2L8** [comment]
It's possible to downgrade to 1.2 to use the mod, right?

**Comment by masagrator** [comment]
If you have 1.2 update dumped, then yes

**Comment by chillsahil** [comment]
Any update on progress? or if it is even possible to update your mod to work with 2.0.0?

**Comment by masagrator** [comment]
> or if it is even possible to update your mod to work with 2.0.0?

Sky is the limit. I have some idea how to do it at low cost with DLC blocked, but for next 2 weeks I'm not in home, so... :P

**Comment by chillsahil** [comment]
That's alright! i have it working right now by downgrading the game.

**Comment by masagrator** [comment]
Released 0.4.1 version that adds support for 2.0.0+ without support for DLC. It was not tested properly, only that everything looks like it should.

**Comment by chillsahil** [comment]
Does this mean that origin mode, the option to just play the 8 main arcs, is not available? If not, are there any plans to implement it?

**Comment by masagrator** [comment]
They changed scenario opcodes with 2.0.0 update and without shindatautil updated to properly support them, there is no chance.

**Comment by chillsahil** [comment]
That's understandable, I am managing right now by using a 100% save file and manually navigating to the chapters i want to play.
